services:
  - type: web
    name: wp-auto-api
    env: image
    region: oregon
    plan: free
    image:
      url: docker.io/trhgatu/wp-publisher-api:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wp-auto-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: wp-auto-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: WP_API_URL
        sync: false
      - key: WP_USERNAME
        sync: false
      - key: WP_APP_PASSWORD
        sync: false

  - type: web
    name: wp-auto-web
    env: static
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm -F @repo/shared build && pnpm -F @repo/web build
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://wp-auto-api.onrender.com

  - type: redis
    name: wp-auto-redis
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all inclusive for testing

databases:
  - name: wp-auto-db
    databaseName: wp_publisher_db
    user: admin_wp
    region: oregon
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all inclusive for testing
